/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-10 04:05:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.calorie.exercise;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;

public final class exercise_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/view/calorie/exercise/../../common/sidebar.jsp", Long.valueOf(1552151808071L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>DIE DIE</title>\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/diedie/assets/css/main.css\" />\r\n");
      out.write("\t\t<script src=\"/diedie/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\tsection { border-top: none !important; }\r\n");
      out.write("\t\t\ttable th { text-align: center !important; }\r\n");
      out.write("\t\t\t.mytable { text-align: center; }\r\n");
      out.write("\t\t\t.mytable button { box-shadow: inset 0 0 0 1px #f56a6a; height: 3em; line-height: 3em; padding: 0 2em; }\r\n");
      out.write("\t\t\t.hidetext { display: none !important; }\r\n");
      out.write("\t\t\tinput[type=date]::-webkit-inner-spin-button,\r\n");
      out.write("\t\t\tinput[type=date]::-webkit-outer-spin-button {\r\n");
      out.write("    \t\t\t-webkit-appearance: none;\r\n");
      out.write("   \t\t\t\t margin: 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\t\r\n");
      out.write("\t\t\tfunction exerexer(){\r\n");
      out.write("\t\t\t\tvar searche = $(\"#searchexer\").val();\r\n");
      out.write("\t\t\t\tif(searche.length == 0 || searche == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"검색할 운동명을 입력해 주십시오.\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl: \"/diedie/esearch\",\r\n");
      out.write("\t\t\t\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\t\t\t\tdata: {searchexer: searche},\r\n");
      out.write("\t\t\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\t\t\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar values = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(json.list.length != 0){\r\n");
      out.write("\t\t\t\t\t\t\t\tfor(var i in json.list){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalues += \"<tr><td></td><td>\" + i + \"</td><td>\" + decodeURIComponent(json.list[i].ename).replace(/\\+/gi, \" \") +\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"</td><td>\" + json.list[i].etime + \"</td><td>\" + json.list[i].ecalorie +\"</td><td><button onclick='goexerdetail(\" + json.list[i].eno + \");'>상세보기</button></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tvalues += \"<tr><td colspan='6'>검색 결과가 없습니다.</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#exerlist\").html(values);\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror: function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + testStatus + \", \" + errorThrown);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}); //ajax\r\n");
      out.write("\t\t\t\t} //ifelse\r\n");
      out.write("\t\t\t}; //exerexer\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction goexerdetail(data){\r\n");
      out.write("\t\t\t\twindow.open(\"/diedie/edetail?eno=\" + data, 'DIE DIE', 'width=400, height=560');\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar selectArray = new Array();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction imchange(){\r\n");
      out.write("\t\t\t\tvar text = $(\"#childcommon\").val();\r\n");
      out.write("\t\t\t\tif(selectArray[0] == null){\r\n");
      out.write("\t\t\t\t\tselectArray[0] = text;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tselectArray[selectArray.length] = text;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar exervalues = \"\";\r\n");
      out.write("\t\t\t\tfor(var i in selectArray){\r\n");
      out.write("\t\t\t\t\tif(selectArray[i] != 0){\r\n");
      out.write("\t\t\t\t\t\tvar exervalue = selectArray[i].split(\",\");\r\n");
      out.write("\t\t\t\t\t\texervalues += \"<tr><td>\" + i + \"</td><td>\" + exervalue[0] +\r\n");
      out.write("\t\t\t\t\t\t\"</td><td>\" + exervalue[1] + \"</td><td>\" + exervalue[2] +\r\n");
      out.write("\t\t\t\t\t\t\"</td><td><button onclick='deleterow(\" + i + \");'>삭제</button></td></tr>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#selectlist\").html(exervalues);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar gogosh = \"<tr><td></td><td>연동 날짜 : </td><td><input type='date' id='imdate'></td>\" + \r\n");
      out.write("\t\t\t\t\"<td colspan='2'><button>내 스케쥴러에 연동하기</button></td></tr>\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#goscheduler\").html(gogosh);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdocument.getElementById('imdate').value = new Date().toISOString().slice(0, 10);\r\n");
      out.write("\t\t\t}; //imchange\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction deleterow(no){\r\n");
      out.write("\t\t\t\tselectArray[no] = 0;\r\n");
      out.write("\t\t\t\tvar exervalues = \"\";\r\n");
      out.write("\t\t\t\tfor(var i in selectArray){\r\n");
      out.write("\t\t\t\t\tif(selectArray[i] != 0){\r\n");
      out.write("\t\t\t\t\t\tvar exervalue = selectArray[i].split(\",\");\r\n");
      out.write("\t\t\t\t\t\texervalues += \"<tr><td>\" + i + \"</td><td>\" + exervalue[0] +\r\n");
      out.write("\t\t\t\t\t\t\"</td><td>\" + exervalue[1] + \"</td><td>\" + exervalue[2] +\r\n");
      out.write("\t\t\t\t\t\t\"</td><td><button onclick='deleterow(\" + i + \");'>삭제</button></td></tr>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#selectlist\").html(exervalues);\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Wrapper -->\r\n");
      out.write("\t\t\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Main -->\r\n");
      out.write("\t\t\t\t\t<div id=\"main\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<header id=\"header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/diedie/view/calorie/exercise/exercise.jsp\" class=\"logo\"><strong>운동 칼로리 계산</strong></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Content -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row gtr-uniform\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"searchexer\" id=\"searchexer\" placeholder=\"운동명을 입력하세요.\" onKeyPress=\"if (event.keyCode==13){exerexer();}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"primary\" onclick=\"exerexer();\">검색</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>운동 칼로리 목록</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=table-wrapper style=\"height: 350px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"mytable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>운동명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>운동시간(분)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>60kg 기준 칼로리 소모량(kcal)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"exerlist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>추가한 운동 칼로리</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=table-wrapper style=\"height: 350px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"mytable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>운동명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>운동시간(분)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>칼로리 소모량(kcal)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"selectlist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tfoot id=\"goscheduler\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"hidetext\" type=\"text\" id=\"childcommon\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Content End!!!!!!!! -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Sidebar -->\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");

	User loginUser2 = (User)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>DIE DIE</title>\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/diedie/assets/css/main.css\" />\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t.footerfont { border-bottom: dotted 1px; }\r\n");
      out.write("\t\t\t.footerfont:hover {\r\n");
      out.write("\t\t\tborder-bottom-color: #f56a6a;\r\n");
      out.write("\t\t\tcolor: #f56a6a !important;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<!-- Sidebar -->\r\n");
      out.write("\t\t<div id=\"sidebar\">\r\n");
      out.write("\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t\t<section class=\"alt\">\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mini-posts\">\r\n");
      out.write("\t\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/diedie/index.jsp\" class=\"image\"><img src=\"/diedie/images/logo2.png\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Menu -->\r\n");
      out.write("\t\t\t\t\t<nav id=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>&nbsp;메뉴</h2>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 샘픔데이터. 나중에 지워야 함 -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/diedie/generic.html\">generic</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/diedie/elements.html\">elememnts</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/diedie/index.jsp\">&nbsp;홈</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(loginUser2 == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/diedie/view/login/login.jsp\">&nbsp;로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/diedie/view/join/join.jsp\">&nbsp;회원가입</a></li>\r\n");
      out.write("\t\t                    ");
 }else{ 
      out.write("\r\n");
      out.write("\t\t                     <li><a href=\"/diedie/logout\">&nbsp;로그아웃</a></li>\r\n");
      out.write("\t\t                     <li>\r\n");
      out.write("\t\t                        <span class=\"opener\">&nbsp;마이페이지</span>\r\n");
      out.write("\t\t                        <ul>\r\n");
      out.write("\t\t                           <li><a href=\"/diedie/view/mypage/mypage.jsp\">&nbsp;내 정보</a></li>\r\n");
      out.write("\t\t                           <li><a href=\"/diedie/view/mypage/userUpdatePage.jsp\">&nbsp;회원정보 수정</a></li>\r\n");
      out.write("\t\t                           <li><a href=\"#\">&nbsp;비밀번호 변경</a></li>\r\n");
      out.write("\t\t                           <li><a href=\"#\">&nbsp;회원탈퇴</a></li>\r\n");
      out.write("\t\t                        </ul>\r\n");
      out.write("\t\t                     </li>\r\n");
      out.write("\t\t                     ");
 } 
      out.write("\r\n");
      out.write("\t\t                     <li>\r\n");
      out.write("                        <span class=\"opener\">&nbsp;칼로리</span>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><a href=\"/diedie/view/calorie/food/food.jsp\">&nbsp;음식칼로리</a></li>\r\n");
      out.write("                           <li><a href=\"/diedie/view/calorie/exercise/exercise.jsp\">&nbsp;운동칼로리</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                  \t\t   </li>\r\n");
      out.write("                 \t\t    <li><a href=\"/diedie/view/scheduler/scheduler.jsp\">&nbsp;스케쥴러</a>\r\n");
      out.write("                 \t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(loginUser2 != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/diedie/partner?loginUser=");
      out.print( loginUser2.getUserId() );
      out.write("\">&nbsp;파트너</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/diedie/partner\">&nbsp;파트너</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"opener\">&nbsp;게시판</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/diedie/nlist?page=1\">&nbsp;공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">&nbsp;정보 공유</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">&nbsp;갤러리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">&nbsp;질문 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">&nbsp;자유 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/diedie/view/fitness/fitness.jsp\">&nbsp;생활체육시설</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/diedie/view/service/service.jsp\">&nbsp;고객센터</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"opener\">Another Submenu</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem Dolor</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Ipsum Adipiscing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Tempus Magna</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Feugiat Veroeros</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Section -->\r\n");
      out.write("\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>&nbsp;연락처</h4>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"contact\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"fa-envelope-o\">jjjein13@gmail.com</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t\t\t<footer id=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"copyright\">Copyright ⓒ <font class=\"footerfont\">운동하고건강하조</font> All rights reserved.</p>\r\n");
      out.write("\t\t\t\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"/diedie/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/diedie/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/diedie/assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"/diedie/assets/js/main.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
